services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db

  card-cost-api:
    image: card-cost-api
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: example
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_HOST: mongo
      APP_IINCACHE_TIMEUNIT: hours
    ports:
      - "8080:8080"

volumes:
  mongodb-data:
    driver: local
