app:
  thirdrpovider:
    binlist:
      base-url: "https://lookup.binlist.net"
      max-call:
        count: 5
        time-unit: minutes
        period: 30


  iin-cache:
    timeUnit: minutes
    period: 1
    enabled: true

spring:
  data:
    mongodb:
      authentication-database: admin
      repositories:
        type: reactive
      database: "currency-cost"
      auto-index-creation: true

  jackson:
    default-property-inclusion: non_null
